---
title: "Points Above Replacement"
subtitle: "A New NBA Metric for Player Performance"
author: |
  | Brian Krikorian and Jun Yan
  | brian.krikorian@uconn.edu
  | Department of Statistics, University of Connecticut
date: "`r format(Sys.time(), '%d, %B, %Y')`"
documentclass: article
papersize: letter
fontsize: 11pt
#bibliography: citations.bib
biblio-style: asa
---

```{r data, include=FALSE}
league <- read.csv(file = '~/Documents/GitHub/Spring2022Thesis/Data/League.csv', stringsAsFactors = TRUE, header = TRUE)
```

```{r initialize variables, echo=FALSE}
player<-list(league$Player)
position<-list(league$Pos)
games<-list(league$G)
minutesPlayed<-list(league$MP)
threePointPercentage<-list(league$X3P.)
effectiveFieldGoalPercentage<-list(league$eFG.)
freeThrowPercentage<-list(league$FT.)
offensiveRebounds<-list(league$ORB)
defensiveRebounds<-list(league$DRB)
totalRebounds<-list(league$TRB)
assists<-list(league$AST)
steals<-list(league$STL)
blocks<-list(league$BLK)
turnovers<-list(league$TOV)
personalFouls<-list(league$PF)
points<-list(league$PTS)
PER<-list(league$PER)
trueShooting<-list(league$TS.)
usagePercentage<-list(league$USG.)
winShares<-list(league$WS)
winSharesPer48<-list(league$WS.48)
boxPlusMinus<-list(league$BPM)
valueOver<-list(league$VORP)
teamTotalPoints<-list(league$TeamTotalPoints)
x1<-list(league$X1)
x2<-list(league$X2)
x3<-list(league$X3)
x4<-list(league$X4)
x5<-list(league$X5)
x6<-list(league$X6)
x7<-list(league$X7)
x8<-list(league$X8)
x9<-list(league$X9)
x10<-list(league$X10)
x11<-list(league$X11)
x12<-list(league$X12)
```


```{r methods, echo=FALSE}
offensivePoints<-function(x1, effectiveFieldGoalPercentage, x2, threePointPercentage, x3, freeThrowPercentage, x4, offensiveRebounds, x5, assists, x6, points, x7, turnovers)
+ {(x1*effectiveFieldGoalPercentage)+(x2*threePointPercentage)+(x3*freeThrowPercentage)+(x4*offensiveRebounds)+(x5*assists)+(x6*points)+(x7*turnovers)}
NBAOffensivePoints <- mapply(offensivePoints, x1, effectiveFieldGoalPercentage, x2, threePointPercentage, x3, freeThrowPercentage, x4, offensiveRebounds, x5, assists, x6, points, x7, turnovers)
defensivePoints <-function(x8, defensiveRebounds, x9, totalRebounds, x10, steals, x11, blocks, x12, personalFouls)
+ {(x8*defensiveRebounds)+(x9*totalRebounds)+(x10*steals)+(x11*blocks)+(x12*personalFouls)}
NBADefensivePoints<-mapply(defensivePoints, x8, defensiveRebounds, x9, totalRebounds, x10, steals, x11, blocks, x12, personalFouls)
offensiveAndDefensivePoints<-function(NBAOffensivePoints, NBADefensivePoints)
+ {NBAOffensivePoints+NBADefensivePoints}
NBAOffensiveAndDefensivePoints<-mapply(offensiveAndDefensivePoints,NBAOffensivePoints,NBADefensivePoints)
teamAdjustment<-function(minutesPlayed, points, teamTotalPoints)
+ {(minutesPlayed/3456)*(points/teamTotalPoints)}
NBATeamAdjustment<-mapply(teamAdjustment, minutesPlayed, points, teamTotalPoints)
pointsPerWin<-function(NBAOffensiveAndDefensivePoints, minutesPlayed)
+  {((NBAOffensiveAndDefensivePoints)/minutesPlayed)+2160}
NBAPointsPerWin<-diag(mapply(pointsPerWin, NBAOffensiveAndDefensivePoints, minutesPlayed))
PAR<-function(NBAOffensiveAndDefensivePoints, NBATeamAdjustment, NBAPointsPerWin)
+ {(NBAOffensiveAndDefensivePoints*NBATeamAdjustment)/NBAPointsPerWin}
NBAPAR<-diag(diag(mapply(PAR, NBAOffensiveAndDefensivePoints,NBATeamAdjustment,NBAPointsPerWin)))
print('NBA PAR')
```

```{r scaling factors, echo=FALSE}
scaledOffensivePoints<-scale(NBAOffensivePoints, center = TRUE, scale = TRUE)
scaledDefensivePoints<-scale(NBADefensivePoints, center = TRUE, scale = TRUE)
scaledPointsPerWin<-scale(NBAPointsPerWin, center = TRUE, scale = TRUE)
scaledPAR<-scale(NBAPAR, center = TRUE, scale = TRUE)
```

```{r performing regression, echo=FALSE}
print('Regression of PAR(X) on VORP(Y)')
PARandVORP<-lm(scaledPAR~league$VORP)
summary(PARandVORP)

multipleRegression<-lm(scaledPAR ~ league$PER + league$WS + league$BPM + league$VORP)
print('Multiple Regression: X = PER, WS, BPM, VORP, Y = PAR')
summary(multipleRegression)

nonPARmultipleRegression<-lm(league$VORP ~ league$PER + league$WS + league$BPM )
print('Multiple Regression: X = PER, WS, BPM, VORP, Y = VORP')
summary(nonPARmultipleRegression)

print('ANOVA of Multiple Regression with PAR as Y')
anova(multipleRegression)
```

Plots
```{r plot1, echo = FALSE}
print('Plots of Multiple Regression with PAR as Y')
plot(multipleRegression)

legend<-quantile(scaledPAR, probs = c(0, 0.5, 0.75, 0.9, 0.95, 1))
print("Breaking PAR into 5 groups")
print(legend)

pdf(file= "/Users/briankrikorian/Documents/GitHub/Spring2022Thesis/Manuscript/figs/VORPvsPAR.pdf", width = 6, height = 6)
plot(league$VORP, scaledPAR, xlab = "VORP", ylab = "PAR")
dev.off()

pdf(file= "/Users/briankrikorian/Documents/GitHub/Spring2022Thesis/Manuscript/figs/WSvsPAR.pdf", width = 6, height = 6)
plot(league$WS, scaledPAR,  xlab = "WS", ylab = "PAR")
dev.off()

pdf(file= "/Users/briankrikorian/Documents/GitHub/Spring2022Thesis/Manuscript/figs/BPMvsPAR.pdf", width = 6, height = 6)
plot(league$BPM, scaledPAR, xlab = "BPM", ylab = "PAR")
dev.off()

pdf(file= "/Users/briankrikorian/Documents/GitHub/Spring2022Thesis/Manuscript/figs/PERvsPAR.pdf", width = 6, height = 6)
plot(league$PER, scaledPAR, xlab = "PER", ylab = "PAR")
dev.off()
```

