---
title: "Points Above Replacement"
subtitle: "A New NBA Metric for Player Performance"
author: |
  | Brian Krikorian and Jun Yan
  | brian.krikorian@uconn.edu
  | Department of Statistics, University of Connecticut
date: "`r format(Sys.time(), '%d, %B, %Y')`"
documentclass: article
papersize: letter
fontsize: 11pt
#bibliography: citations.bib
biblio-style: asa
---

```{r data, include=FALSE}
pointGuards <- read.csv(file = '~/Documents/GitHub/Spring2022Thesis/PointGuards.csv', stringsAsFactors = TRUE, header = TRUE)
```

```{r initialize variables, echo=FALSE}
position<-list(pointGuards$Pos)
games<-list(pointGuards$G)
minutesPlayed<-list(pointGuards$MP)
fieldGoalPercentage<- list(pointGuards$FG.)
threePointPercentage<-list(pointGuards$X3P.)
twoPointPercentage<-list(pointGuards$X2P.)
effectiveFieldGoalPercentage<-list(pointGuards$eFG.)
freeThrowPercentage<-list(pointGuards$FT.)
offensiveRebounds<-list(pointGuards$ORB)
defensiveRebounds<-list(pointGuards$DRB)
totalRebounds<-list(pointGuards$TRB)
assists<-list(pointGuards$AST)
steals<-list(pointGuards$STL)
blocks<-list(pointGuards$BLK)
turnovers<-list(pointGuards$TOV)
personalFouls<-list(pointGuards$PF)
points<-list(pointGuards$PTS)
player<-list(pointGuards$Player)
pointsPerMinute<-list(pointGuards$PPM)
PER<-list(pointGuards$PER)
trueShooting<-list(pointGuards$TS.)
usagePercentage<-list(pointGuards$USG.)
winShares<-list(pointGuards$WS)
winSharesPer48<-list(pointGuards$WS.48)
boxPlusMinus<-list(pointGuards$BPM)
valueOver<-list(pointGuards$VORP)
teamTotalPoints<-list(pointGuards$TeamTotalPoints)
```

```{r methods, echo=FALSE}
offensivePoints<-function(effectiveFieldGoalPercentage, threePointPercentage, freeThrowPercentage, offensiveRebounds, assists, points, turnovers)
+ {(200*effectiveFieldGoalPercentage)+(300*threePointPercentage)+(100*freeThrowPercentage)+(offensiveRebounds)+(3*assists)+(2*points)-(5*turnovers)}
pgOffensivePoints <- mapply(offensivePoints, effectiveFieldGoalPercentage, threePointPercentage, freeThrowPercentage, offensiveRebounds, assists, points, turnovers)
defensivePoints <-function(defensiveRebounds, totalRebounds, steals, blocks, personalFouls)
+ {(2*defensiveRebounds)+(3*totalRebounds)+(5*steals)+(3*blocks)-(3*personalFouls)}
pgDefensivePoints<-mapply(defensivePoints, defensiveRebounds, totalRebounds, steals, blocks, personalFouls)
offensiveAndDefensivePoints<-function(pgOffensivePoints, pgDefensivePoints)
+ {pgOffensivePoints+pgDefensivePoints}
pgOffensiveAndDefensivePoints<-mapply(offensiveAndDefensivePoints,pgOffensivePoints,pgDefensivePoints)
positionalAdjustment<-function(minutesPlayed, points, teamTotalPoints)
+ {(minutesPlayed/3456)*(points/teamTotalPoints)}
pgPositionalAdjustment<-mapply(positionalAdjustment, minutesPlayed, points, teamTotalPoints)
pointsPerWin<-function(pgOffensiveAndDefensivePoints, minutesPlayed)
+  {48*((pgOffensiveAndDefensivePoints)/minutesPlayed)*8+72}
pgPointsPerWin<-diag(mapply(pointsPerWin, pgOffensiveAndDefensivePoints, minutesPlayed))
PAR<-function(pgOffensiveAndDefensivePoints, pgPositionalAdjustment, pgPointsPerWin)
+ {(pgOffensiveAndDefensivePoints*pgPositionalAdjustment)/pgPointsPerWin}
pgPAR<-diag(diag(mapply(PAR, pgOffensiveAndDefensivePoints,pgPositionalAdjustment,pgPointsPerWin)))
print('PAR Data')
print(pgPAR)
```

```{r scaling factors, echo=FALSE}
scaledOffensivePoints<-scale(pgOffensivePoints, center = TRUE, scale = TRUE)
scaledDefensivePoints<-scale(pgDefensivePoints, center = TRUE, scale = TRUE)
scaledPointsPerWin<-scale(pgPointsPerWin, center = TRUE, scale = TRUE)
scaledPAR<-scale(pgPAR, center = TRUE, scale = TRUE)
```

```{r performing regression, echo=FALSE}
PPM<-as.numeric(pointGuards$PPM)
regressionPPMonPAR<-lm(scaledPAR ~ PPM)
print('Regression of PPM(X) on PAR(Y)')
summary(regressionPPMonPAR)

print('Regression of PAR(X) on VORP(Y)')
PARandVORP<-lm(scaledPAR~pointGuards$VORP)
summary(PARandVORP)
plot(pointGuards$VORP, scaledPAR)

print('Regression of PAR(X) on BPM(Y)')
PARandBPM<-lm(scaledPAR~pointGuards$BPM)
summary(PARandBPM)
plot(pointGuards$BPM, scaledPAR)

multipleRegression<-lm(scaledPAR ~ pointGuards$PER + pointGuards$WS + pointGuards$BPM + pointGuards$VORP)
print('Multiple Regression: X = PER, WS, BPM, VORP, Y = PAR')
summary(multipleRegression)

nonPARmultipleRegression<-lm(pointGuards$VORP ~ pointGuards$PER + pointGuards$WS + pointGuards$BPM )
print('Multiple Regression: X = PER, WS, BPM, VORP, Y = VORP')
summary(nonPARmultipleRegression)

print('ANOVA of Multiple Regression with PAR as Y')
anova(multipleRegression)
```

Plots
```{r plot1, echo = FALSE}
print('Plots of Multiple Regression with PAR as Y')
plot(multipleRegression)
```
```{r plot2, echo = FALSE}
print('Plots of Regression of PPM (X) on PAR (Y)')
plot(regressionPPMonPAR)
```
